// This file is auto-generated by @hey-api/openapi-ts

/**
 * Key to identify a video.
 */
export type VideoKey = {
    myAnimeListId: number;
    dub: string;
    episode: number;
};

/**
 * Interval of time in seconds.
 */
export type Interval = {
    start: number;
    end: number;
};

/**
 * Scenes of a video. If a scene is not present, it means that it is not recognised.
 */
export type Scenes = {
    opening?: Interval;
    ending?: Interval;
    sceneAfterEnding?: Interval;
};

export type SceneRecognisedNotificationItem = VideoKey & {
    scenes?: Scenes;
};

/**
 * Notification that video scenes have been recognised (for multiple videos at once)
 */
export type SceneRecognisedNotification = {
    items: Array<SceneRecognisedNotificationItem>;
};

/**
 * Notification that a video has been downloaded
 */
export type VideoDownloadedNotification = VideoKey & {
    messageId?: number;
};

export type VideoRegisteredNotificationItem = VideoKey;

/**
 * Notification that a video has been registered (for multiple videos at once)
 */
export type VideoRegisteredNotification = {
    items: Array<VideoRegisteredNotificationItem>;
};

/**
 * List of a videos to match
 */
export type MatcherResponse = {
    videosToMatch: Array<VideoKey>;
};

export type MatcherResultRequestItem = VideoKey & {
    scenes: Scenes;
};

/**
 * Request to send the result of the matching
 */
export type MatcherResultRequest = {
    items: Array<MatcherResultRequestItem>;
};

/**
 * A video to download
 */
export type DownloaderResponse = {
    videoKey?: VideoKey;
};

/**
 * Request to send the result of the download
 */
export type DownloaderResultRequest = VideoKey & {
    messageId?: number;
};

/**
 * Request to send from the bot tp AniMan
 */
export type BotRequest = VideoKey & {
    chatId: number;
};

/**
 * Response to send from AniMan to the bot
 */
export type BotResponse = {
    status: VideoStatus;
    messageId?: number;
    scenes?: Scenes;
};

/**
 * Status of a video
 */
export type VideoStatus = 'Pending' | 'Downloading' | 'Downloaded' | 'Failed' | 'NotAvailable';