# coding: utf-8

"""
    Bounan.Common models

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bounan_common.models.scenes import Scenes

class TestScenes(unittest.TestCase):
    """Scenes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Scenes:
        """Test Scenes
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Scenes`
        """
        model = Scenes()
        if include_optional:
            return Scenes(
                opening = bounan_common.models.interval.Interval(
                    start = 1.337, 
                    end = 1.337, ),
                ending = bounan_common.models.interval.Interval(
                    start = 1.337, 
                    end = 1.337, ),
                scene_after_ending = bounan_common.models.interval.Interval(
                    start = 1.337, 
                    end = 1.337, )
            )
        else:
            return Scenes(
        )
        """

    def testScenes(self):
        """Test Scenes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
