# coding: utf-8

"""
    Bounan.Common models

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bounan_common.models.video_status import VideoStatus

class TestVideoStatus(unittest.TestCase):
    """VideoStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVideoStatus(self):
        """Test VideoStatus"""
        # inst = VideoStatus()

if __name__ == '__main__':
    unittest.main()
