# coding: utf-8

"""
    Bounan.Common models

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bounan_common.models.interval import Interval

class TestInterval(unittest.TestCase):
    """Interval unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Interval:
        """Test Interval
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Interval`
        """
        model = Interval()
        if include_optional:
            return Interval(
                start = 1.337,
                end = 1.337
            )
        else:
            return Interval(
                start = 1.337,
                end = 1.337,
        )
        """

    def testInterval(self):
        """Test Interval"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
