# coding: utf-8

"""
    Bounan.Common models

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bounan_common.models.scene_recognised_notification import SceneRecognisedNotification

class TestSceneRecognisedNotification(unittest.TestCase):
    """SceneRecognisedNotification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SceneRecognisedNotification:
        """Test SceneRecognisedNotification
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SceneRecognisedNotification`
        """
        model = SceneRecognisedNotification()
        if include_optional:
            return SceneRecognisedNotification(
                items = [
                    null
                    ]
            )
        else:
            return SceneRecognisedNotification(
                items = [
                    null
                    ],
        )
        """

    def testSceneRecognisedNotification(self):
        """Test SceneRecognisedNotification"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
